const tableData = {
    "data": [
        {
            "pos_x_on_top": 0,
            "size_z": 6,
            "express_station": 0,
            "size_y": 10.46,
            "size_x": 3.98,
            "ID_user_change": 999,
            "description": "fffffff",
            "ID_station": 3,
            "pos_y_on_top": 0,
            "ID_wh": 18655,
            "pos_y": 13.95,
            "on_top": 6,
            "pos_x": 0.98,
            "back_color": "#ade",
            "text": "Inbound",
            "on_empty_remove_assignment": false,
            "solid": true,
            "enable_background_image": false,
            "border_color": "#333",
            "keep_size": true,
            "ID_io_creation": 1,
            "visualization_type": 0,
            "ID_mtm": 1,
            "changed": "2022-11-11 18:10:05"
        },
        {
            "pos_x_on_top": 0,
            "size_z": 6,
            "express_station": 0,
            "size_y": 3.99,
            "size_x": 7.77,
            "ID_user_change": 999,
            "description": "fffffff",
            "ID_station": 6,
            "pos_y_on_top": 0,
            "ID_wh": 18655,
            "pos_y": 21.25,
            "on_top": 26884,
            "pos_x": 50.42,
            "back_color": "#bb6",
            "text": "Automation packing",
            "on_empty_remove_assignment": false,
            "solid": true,
            "enable_background_image": false,
            "border_color": "#bb6",
            "keep_size": false,
            "ID_io_creation": 1,
            "visualization_type": 0,
            "ID_mtm": 1,
            "changed": "2022-11-22 17:54:04"
        },
        {
            "pos_x_on_top": 0,
            "size_z": 6,
            "express_station": 3,
            "size_y": 14.59,
            "size_x": 9.49,
            "ID_user_change": 999,
            "description": "qwe",
            "ID_station": 7,
            "pos_y_on_top": 0,
            "ID_wh": 18655,
            "pos_y": 0,
            "pos_x": 0,
            "back_color": "#FFF",
            "text": "DockArea",
            "on_empty_remove_assignment": false,
            "solid": false,
            "enable_background_image": false,
            "border_color": "#333",
            "keep_size": false,
            "ID_io_creation": 60880,
            "visualization_type": 0,
            "ID_mtm": 1,
            "changed": "2022-11-25 15:47:14"
        },
        {
            "pos_x_on_top": 0,
            "size_z": 5,
            "express_station": 1,
            "size_y": 16.85,
            "size_x": 28.79,
            "ID_user_change": 999,
            "description": "qwe",
            "ID_station": 6088,
            "pos_y_on_top": 0,
            "ID_wh": 18655,
            "pos_y": 20,
            "on_top": 0,
            "pos_x": 6.26,
            "back_color": "#ba22ba",
            "text": "StorageSouth",
            "on_empty_remove_assignment": true,
            "solid": true,
            "enable_background_image": false,
            "border_color": "#fff",
            "keep_size": true,
            "ID_io_creation": 42165,
            "visualization_type": 0,
            "ID_mtm": 1,
            "changed": "2022-11-22 17:54:05"
        },
        {
            "pos_x_on_top": 0,
            "size_z": 4,
            "express_station": 0,
            "size_y": 34.33,
            "size_x": 12.44,
            "ID_user_change": 999,
            "description": "qwe",
            "ID_station": 12463,
            "pos_y_on_top": 0,
            "ID_wh": 18655,
            "pos_y": 1.55,
            "on_top": 0,
            "pos_x": 35.74,
            "back_color": "#dd8",
            "text": "Forvard Area",
            "on_empty_remove_assignment": false,
            "solid": false,
            "enable_background_image": false,
            "border_color": "#333",
            "keep_size": false,
            "ID_io_creation": 1,
            "visualization_type": 0,
            "ID_mtm": 1,
            "changed": "2022-11-25 16:00:12"
        },
        {
            "pos_x_on_top": 0,
            "size_z": 5,
            "express_station": 2,
            "size_y": 17.1,
            "size_x": 28.58,
            "ID_user_change": 999,
            "description": "qwe",
            "ID_station": 14879,
            "pos_y_on_top": 0,
            "ID_wh": 18655,
            "pos_y": 0.76,
            "on_top": 0,
            "pos_x": 6.3,
            "back_color": "#bd11bd",
            "text": "StorageNorth",
            "on_empty_remove_assignment": false,
            "solid": true,
            "enable_background_image": false,
            "border_color": "#fff",
            "keep_size": true,
            "ID_io_creation": 42165,
            "visualization_type": 0,
            "ID_mtm": 1,
            "changed": "2022-11-07 20:08:31"
        },
        {
            "pos_x_on_top": 0,
            "size_z": 6,
            "express_station": 3,
            "size_y": 15.99,
            "size_x": 9.02,
            "ID_user_change": 999,
            "description": "asdasd",
            "ID_station": 26884,
            "pos_y_on_top": 0,
            "ID_wh": 18655,
            "pos_y": 1.4,
            "on_top": 0,
            "pos_x": 49.22,
            "back_color": "#da8",
            "text": "Fast area",
            "on_empty_remove_assignment": false,
            "solid": true,
            "enable_background_image": true,
            "border_color": "#333",
            "keep_size": false,
            "ID_io_creation": 1,
            "visualization_type": 0,
            "ID_mtm": 1,
            "changed": "2022-11-08 15:06:05"
        }
    ],
    "totalCount": 7,
    "summary": []
};

export default tableData;