/*******************************************************************************
 * (C) Copyright
 * Logivations GmbH, Munich 2010-2022
 ******************************************************************************/

import translate from '../i18n/localization';

const tabTitleConstants = [
	{ id: 'LAYOUT_NAME_TABLE_NAME', name: translate('LAYOUT_NAME_TABLE_NAME') },
	{ id: 'TABLE_NAME_LAYOUT_NAME', name: translate('TABLE_NAME_LAYOUT_NAME') },
];

enum StoreSettingKey {
	DBE_VIEW_MODE_SETTINGS = 'DBE_VIEW_MODE_SETTINGS',
	DBE_TAB_TITLE_SETTINGS = 'DBE_TAB_TITLE_SETTINGS',
	DBE_PAGE_SIZE_SETTINGS = 'DBE_PAGE_SIZE_SETTINGS',
	DBE_SCREEN_BUILDER_SETTINGS = 'DBE_SCREEN_BUILDER_SETTINGS',
	DBE_IS_AUTO_REFRESH_SETTINGS = 'DBE_IS_AUTO_REFRESH_SETTINGS',
	DBE_REPORT_PARAMETERS_SETTING = 'DBE_REPORT_PARAMETERS_SETTING',
	DBE_INTERVAL_IN_SECONDS_SETTINGS = 'DBE_INTERVAL_IN_SECONDS_SETTINGS',
	DBE_IS_LAST_SELECTION_MODE_SETTINGS = 'DBE_IS_LAST_SELECTION_MODE_SETTINGS',
	DBE_TABLE_ACTION_PARAMETERS_SETTING = 'DBE_TABLE_ACTION_PARAMETERS_SETTING',
	DBE_IS_FLEXIBLE_TOOLBAR_PANEL_SETTINGS = 'DBE_IS_FLEXIBLE_TOOLBAR_PANEL_SETTINGS',
	DBE_CHILD_PARENT_DETAILS_INFO_SETTINGS = 'DBE_CHILD_PARENT_DETAILS_INFO_SETTINGS',
	DBE_ADVANCED_FILTER_PAGE_SIZE_SETTINGS = 'DBE_ADVANCED_FILTER_PAGE_SIZE_SETTINGS',
	DBE_IMPORT_DATE_FORMAT_PATTERN_SETTING = 'DBE_IMPORT_DATE_FORMAT_PATTERN_SETTING',
	DBE_SORT_ORDER_SETTING = 'DBE_SORT_ORDER_SETTING',
	DBE_FILTER_SETTING = 'DBE_FILTER_SETTING',
	DBE_GROUPING_FILTER_SETTING = 'DBE_GROUPING_FILTER_SETTING',
	DBE_DEFAULT_FILTER_SETTING = 'DBE_DEFAULT_FILTER_SETTING',
	DBE_DEFAULT_SORT_ORDER_SETTING = 'DBE_DEFAULT_SORT_ORDER_SETTING',
	DBE_HIDDEN_COLUMNS_FILTER_SETTING = 'DBE_HIDDEN_COLUMNS_FILTER_SETTING',
	DBE_DEFAULT_GROUPING_FILTER_SETTING = 'DBE_DEFAULT_GROUPING_FILTER_SETTING',
	DBE_DEFAULT_HIDDEN_COLUMNS_FILTER_SETTING = 'DBE_DEFAULT_HIDDEN_COLUMNS_FILTER_SETTING',
	DX_DBE_CHILDREN_TABLE_SETTINGS = 'DX_DBE_CHILDREN_TABLE_SETTINGS',
	DX_DBE_PARENT_TABLE_SETTINGS = 'DX_DBE_PARENT_TABLE_SETTINGS',
	DX_DBE_SCREEN_BUILDER_SETTINGS = 'dxScreenBuilder',
	DX_DBE_PARENT_CHILD_TABLE_SETTINGS = 'dxParentChildTableBuilder',
}

enum EndPoints {
	DBE_FILTER_SETTING = 'storeDxDbeUserFilter',
	DBE_SORT_ORDER_SETTING = 'storeDxDbeSortOrder',
	DBE_GROUPING_FILTER_SETTING = 'storeDxDbeGroupingFilter',
	DBE_HIDDEN_COLUMNS_FILTER_SETTING = 'storeDxDbeHiddenColumnsFilter',
	DBE_SPLIT_SCREEN_PARAMS = 'storeDxSplitScreenParams',
	DBE_GRID_COMMON_SETTINGS = 'storeDxGridCommonSettings',
}

export { tabTitleConstants, StoreSettingKey, EndPoints };
